### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by HydraSparky** [lucasvinbr/GTA5GangMod#17]
When i start my game i get this in the console:

[20:26:42] [ERROR] Caught fatal unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.GangAndTurfMod.GangMemberUpdater.OnTick(Object sender, EventArgs e)
   at SHVDN.Script.MainLoop()
[20:26:42] [ERROR] The exception was thrown while executing the script GTA.GangAndTurfMod.GangMemberUpdater.
[20:26:42] [WARNING] Aborted script GTA.GangAndTurfMod.GangMemberUpdater.
[20:26:46] [ERROR] Caught fatal unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.GangAndTurfMod.MindControl.get_CurrentPlayerCharacter()
   at GTA.GangAndTurfMod.ZoneManager.GetCurrentTurfZone()
   at GTA.GangAndTurfMod.AmbientGangMemberSpawner.OnTick(Object sender, EventArgs e)
   at SHVDN.Script.MainLoop()
[20:26:46] [ERROR] The exception was thrown while executing the script GTA.GangAndTurfMod.AmbientGangMemberSpawner.
[20:26:46] [WARNING] Aborted script GTA.GangAndTurfMod.AmbientGangMemberSpawner.
[20:26:46] [ERROR] Caught fatal unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.GangAndTurfMod.MindControl.get_CurrentPlayerCharacter()
   at GTA.GangAndTurfMod.WorldLocChecker.OnTick(Object sender, EventArgs e)
   at SHVDN.Script.MainLoop()
[20:26:46] [ERROR] The exception was thrown while executing the script GTA.GangAndTurfMod.WorldLocChecker.
[20:26:46] [WARNING] Aborted script GTA.GangAndTurfMod.WorldLocChecker.

And doing Reload() doesnt fix it. I have no idea why its doing this, it was working fine before and nothing changed and it doesnt want to work anymore.

**Comment by lucasvinbr** [comment]
Is that all that's written in the log or there is more before that?
Which version of the hooks are you using?

**Comment by HydraSparky** [comment]
> Is that all that's written in the log or there is more before that?
> Which version of the hooks are you using?

Thats the only error in the log, also latest version of both SHVDN and SHV. Also i figured out the source of this error was me deleting my relationships.dat and agitated ped triggers file in my mods folder.  I deleted them because they were modified from some other mod and it was messing with the gameplay a little. Replacing them fixed the mod.
