### ISSUE TITLE
Help me [ERROR MOD NOT LOADING]

### ISSUE THREAD

**Issue by Luke20202** [lucasvinbr/GTA5GangMod#29]
Ok so I have been trying for the past few weeks to get this mod to work and i have found nothing online to help me with my issue can someone tell me whats wrong and how to fix my issue please because I have seen a few others without a solution aswell.
here is a section from my error info. the mod just wont load into my game.

[20:38:57] [DEBUG] Instantiating script GTA.GangAndTurfMod.ModCore ...
[20:39:00] [ERROR] Failed to instantiate script GTA.GangAndTurfMod.ModCore because constructor threw an exception: System.TypeLoadException: Could not load type 'NativeUI.UIMenuDynamicListItem' from assembly 'NativeUI, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null'.
   at GTA.GangAndTurfMod.CustomZonesSubMenu.Setup()
   at GTA.GangAndTurfMod.ZonesMenu..ctor(MenuPool menuPool)
   at GTA.GangAndTurfMod.MenuScript..ctor()
   at GTA.GangAndTurfMod.ModCore..ctor()
[20:39:00] [DEBUG] Instantiating script GTA.GangAndTurfMod.WorldLocChecker ...
[20:39:00] [INFO] Started script GTA.GangAndTurfMod.WorldLocChecker.
[20:39:00] [DEBUG] Instantiating script LiveryChanger ...
[20:39:00] [INFO] Started script LiveryChanger.
[20:39:00] [DEBUG] Instantiating script NativeUI.BigMessageThread ...
[20:39:00] [INFO] Started script NativeUI.BigMessageThread.
[20:39:00] [DEBUG] Instantiating script ParkedCarReplacement ...
[20:39:00] [INFO] Started script ParkedCarReplacement.
[20:39:00] [DEBUG] Instantiating script BetterChases ...
[20:39:00] [INFO] Started script BetterChases.
[20:39:00] [DEBUG] Instantiating script BetterChasesMessageQueue ...
[20:39:00] [INFO] Started script BetterChasesMessageQueue.
[20:39:00] [DEBUG] Instantiating script BetterChasesUI ...
[20:39:00] [INFO] Started script BetterChasesUI.
[20:39:00] [DEBUG] Instantiating script BetterChasesWantedLevelInstantCopHandler ...
[20:39:00] [INFO] Started script BetterChasesWantedLevelInstantCopHandler.
[20:39:00] [DEBUG] Instantiating script EntityGetter ...
[20:39:00] [INFO] Started script EntityGetter.
[20:39:00] [DEBUG] Instantiating script IncidentManager ...
[20:39:00] [INFO] Started script IncidentManager.
[20:39:00] [DEBUG] Instantiating script SixStar_AI_Buzzard ...
[20:39:00] [INFO] Started script SixStar_AI_Buzzard.
[20:39:00] [DEBUG] Instantiating script SixStar_AI_Generic_Chopper ...
[20:39:00] [INFO] Started script SixStar_AI_Generic_Chopper.
[20:39:00] [DEBUG] Instantiating script SixStar_AI_Generic_Ground ...
[20:39:00] [INFO] Started script SixStar_AI_Generic_Ground.
[20:39:00] [DEBUG] Instantiating script SixStar_AI_Generic_Jet ...
[20:39:00] [INFO] Started script SixStar_AI_Generic_Jet.
[20:39:00] [DEBUG] Instantiating script SixStar_AI_Hydra ...
[20:39:00] [INFO] Started script SixStar_AI_Hydra.
[20:39:00] [DEBUG] Instantiating script SixStar_AI_Lazer ...
[20:39:00] [INFO] Started script SixStar_AI_Lazer.
[20:39:00] [DEBUG] Instantiating script SixStar_AI_Lewd ...
[20:39:00] [INFO] Started script SixStar_AI_Lewd.
[20:39:00] [DEBUG] Instantiating script SixStar_AI_Lewdad ...
[20:39:00] [INFO] Started script SixStar_AI_Lewdad.
[20:39:00] [DEBUG] Instantiating script SixStar_AI_MountedGunners ...
[20:39:00] [INFO] Started script SixStar_AI_MountedGunners.
[20:39:00] [DEBUG] Instantiating script SixStar_AI_Rhino ...
[20:39:00] [INFO] Started script SixStar_AI_Rhino.
[20:39:00] [DEBUG] Instantiating script SixStar_AI_Submarine ...
[20:39:00] [INFO] Started script SixStar_AI_Submarine.
[20:39:00] [DEBUG] Instantiating script SixStar_AI_Valkyrie ...
[20:39:00] [INFO] Started script SixStar_AI_Valkyrie.
[20:39:00] [DEBUG] Instantiating script SixStar_DeleteQueue ...
[20:39:00] [INFO] Started script SixStar_DeleteQueue.
[20:39:00] [DEBUG] Instantiating script SixStar_EntityMonitor ...
[20:39:00] [INFO] Started script SixStar_EntityMonitor.
[20:39:00] [DEBUG] Instantiating script SixStar_SpawnQueue ...
[20:39:00] [INFO] Started script SixStar_SpawnQueue.
[20:39:00] [DEBUG] Instantiating script SixStarResponse ...
[20:39:00] [INFO] Started script SixStarResponse.
[20:39:00] [ERROR] Caught fatal unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.GangAndTurfMod.GangMemberUpdater.OnTick(Object sender, EventArgs e)
   at SHVDN.Script.DoTick()
[20:39:00] [ERROR] The exception was thrown while executing the script GTA.GangAndTurfMod.GangMemberUpdater.
[20:39:00] [ERROR] Caught fatal unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GTA.GangAndTurfMod.GangVehicleUpdater.OnTick(Object sender, EventArgs e)
   at SHVDN.Script.DoTick()
[20:39:00] [ERROR] The exception was thrown while executing the script GTA.GangAndTurfMod.GangVehicleUpdater.
[20:39:00] [WARNING] Aborted script GTA.GangAndTurfMod.GangMemberUpdater.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort()
   at SHVDN.Script.Abort()
   at SHVDN.Script.DoTick()
   at SHVDN.Script.MainLoop()
[20:39:00] [WARNING] Aborted script GTA.GangAndTurfMod.GangVehicleUpdater.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort()
   at SHVDN.Script.Abort()
   at SHVDN.Script.DoTick()
   at SHVDN.Script.MainLoop()

**Comment by lucasvinbr** [comment]
Hi, which version of the mod are you trying to use?
It looks like something is wrong with your NativeUI. It appears to be installed correctly, but it could be outdated. Get the latest version here: https://github.com/Guad/NativeUI/releases

**Comment by Luke20202** [comment]
> Hi, which version of the mod are you trying to use? It looks like something is wrong with your NativeUI. It appears to be installed correctly, but it could be outdated. Get the latest version here: https://github.com/Guad/NativeUI/releases

Ok let me test that out real quick

**Comment by Luke20202** [comment]
> Hi, which version of the mod are you trying to use? It looks like something is wrong with your NativeUI. It appears to be installed correctly, but it could be outdated. Get the latest version here: https://github.com/Guad/NativeUI/releases

DUDE THANKS SO MUCH I THOUGHT I TRIED IT A THOUSAND TIMES BUT IT WAS WITH THE WRONG VERSION!!! Thanks so much bro

**Comment by lucasvinbr** [comment]
haha no problem! I'm glad it's working now
