### ISSUE TITLE
Saving turf data changes overwrites entire file

### ISSUE THREAD

**Issue by freakyneek** [lucasvinbr/GTA5GangMod#5]
Hi,
I discovered a recurring problem while playing your mod for about an hour.  I'm not sure how long the mod takes between saves, but I get a message that the mod saves the turf data. As soon as it does it wipes out all the turf data and leaves only the recent changes made by the turf wars. Every time the mod saves to the turf data file, more turfs are lost if there were no changes between saves.  Eventually, the only turfs left are the ones I have created or those that changed during a turf war since the last save, leaving only a few turf zones.

I'm not a coder, but I dabbled in programming a little bit for education. Something is causing the mod to overwrite the entire file instead of changing turf data or appending new data.

**Comment by lucasvinbr** [comment]
Hey there,
This message you get when the save happens, is it something like "Saved to [file address]"? 
Are the territories themselves, or just their ownerships, removed from the TurfZoneData file when this happens?
Also, did you notice if any error popped up in your scripthookvdotnet.log file?

**Comment by freakyneek** [comment]
I love your mod, by the way. I finally enjoy playing GTA V. It was boring before I installed your mod. Now I'm playing for hours.
1. Yes, it is that same message where it is saving file to [file address].
2. Not just ownership. The whole zone data is erased.
3. Here's a copy of my log.

[00:26:02] [DEBUG] Created script domain 'ScriptDomain_52F2168' with v2.9.2.
[00:26:02] [DEBUG] Loading scripts from 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_52F2168' ...
[00:26:02] [DEBUG] Found 3 script(s) in 'GangAndTurfMod.dll'.
[00:26:02] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[00:26:02] [DEBUG] Found 1 script(s) in 'TriggerHappy.dll'.
[00:26:02] [DEBUG] Starting 5 script(s) ...
[00:26:02] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner' in script domain 'ScriptDomain_52F2168' ...
[00:26:02] [DEBUG] Started script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner'.
[00:26:02] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.GangWarManager' in script domain 'ScriptDomain_52F2168' ...
[00:26:02] [DEBUG] Started script 'GTA.GangAndTurfMod.GangWarManager'.
[00:26:02] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.ModCore' in script domain 'ScriptDomain_52F2168' ...
[00:26:03] [DEBUG] Started script 'GTA.GangAndTurfMod.ModCore'.
[00:26:03] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_52F2168' ...
[00:26:03] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[00:26:03] [DEBUG] Instantiating script 'TriggerHappy.TriggerHappy' in script domain 'ScriptDomain_52F2168' ...
[00:26:03] [DEBUG] Started script 'TriggerHappy.TriggerHappy'.
[01:20:50] [DEBUG] Created script domain 'ScriptDomain_E37E48EE' with v2.9.2.
[01:20:50] [DEBUG] Loading scripts from 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_E37E48EE' ...
[01:20:51] [DEBUG] Found 3 script(s) in 'GangAndTurfMod.dll'.
[01:20:51] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[01:20:51] [DEBUG] Found 1 script(s) in 'TriggerHappy.dll'.
[01:20:51] [DEBUG] Starting 5 script(s) ...
[01:20:51] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner' in script domain 'ScriptDomain_E37E48EE' ...
[01:20:51] [DEBUG] Started script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner'.
[01:20:51] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.GangWarManager' in script domain 'ScriptDomain_E37E48EE' ...
[01:20:51] [DEBUG] Started script 'GTA.GangAndTurfMod.GangWarManager'.
[01:20:51] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.ModCore' in script domain 'ScriptDomain_E37E48EE' ...
[01:20:51] [DEBUG] Started script 'GTA.GangAndTurfMod.ModCore'.
[01:20:51] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_E37E48EE' ...
[01:20:51] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[01:20:51] [DEBUG] Instantiating script 'TriggerHappy.TriggerHappy' in script domain 'ScriptDomain_E37E48EE' ...
[01:20:51] [DEBUG] Started script 'TriggerHappy.TriggerHappy'.
[01:45:15] [DEBUG] Created script domain 'ScriptDomain_51EE62B2' with v2.9.2.
[01:45:15] [DEBUG] Loading scripts from 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_51EE62B2' ...
[01:45:15] [DEBUG] Found 3 script(s) in 'GangAndTurfMod.dll'.
[01:45:15] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[01:45:15] [DEBUG] Found 1 script(s) in 'TriggerHappy.dll'.
[01:45:15] [DEBUG] Starting 5 script(s) ...
[01:45:15] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner' in script domain 'ScriptDomain_51EE62B2' ...
[01:45:15] [DEBUG] Started script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner'.
[01:45:15] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.GangWarManager' in script domain 'ScriptDomain_51EE62B2' ...
[01:45:15] [DEBUG] Started script 'GTA.GangAndTurfMod.GangWarManager'.
[01:45:15] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.ModCore' in script domain 'ScriptDomain_51EE62B2' ...
[01:45:16] [DEBUG] Started script 'GTA.GangAndTurfMod.ModCore'.
[01:45:16] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_51EE62B2' ...
[01:45:16] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[01:45:16] [DEBUG] Instantiating script 'TriggerHappy.TriggerHappy' in script domain 'ScriptDomain_51EE62B2' ...
[01:45:16] [DEBUG] Started script 'TriggerHappy.TriggerHappy'.
[03:08:52] [DEBUG] Created script domain 'ScriptDomain_C0D568B6' with v2.9.2.
[03:08:52] [DEBUG] Loading scripts from 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_C0D568B6' ...
[03:08:52] [DEBUG] Found 3 script(s) in 'GangAndTurfMod.dll'.
[03:08:52] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[03:08:52] [DEBUG] Found 1 script(s) in 'TriggerHappy.dll'.
[03:08:52] [DEBUG] Starting 5 script(s) ...
[03:08:52] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner' in script domain 'ScriptDomain_C0D568B6' ...
[03:08:52] [DEBUG] Started script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner'.
[03:08:52] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.GangWarManager' in script domain 'ScriptDomain_C0D568B6' ...
[03:08:52] [DEBUG] Started script 'GTA.GangAndTurfMod.GangWarManager'.
[03:08:52] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.ModCore' in script domain 'ScriptDomain_C0D568B6' ...
[03:08:53] [DEBUG] Started script 'GTA.GangAndTurfMod.ModCore'.
[03:08:53] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_C0D568B6' ...
[03:08:53] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[03:08:53] [DEBUG] Instantiating script 'TriggerHappy.TriggerHappy' in script domain 'ScriptDomain_C0D568B6' ...
[03:08:53] [DEBUG] Started script 'TriggerHappy.TriggerHappy'.
[03:45:01] [DEBUG] Created script domain 'ScriptDomain_594C2060' with v2.9.2.
[03:45:01] [DEBUG] Loading scripts from 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_594C2060' ...
[03:45:01] [DEBUG] Found 3 script(s) in 'GangAndTurfMod.dll'.
[03:45:01] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[03:45:01] [DEBUG] Found 1 script(s) in 'TriggerHappy.dll'.
[03:45:01] [DEBUG] Starting 5 script(s) ...
[03:45:01] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner' in script domain 'ScriptDomain_594C2060' ...
[03:45:01] [DEBUG] Started script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner'.
[03:45:01] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.GangWarManager' in script domain 'ScriptDomain_594C2060' ...
[03:45:01] [DEBUG] Started script 'GTA.GangAndTurfMod.GangWarManager'.
[03:45:01] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.ModCore' in script domain 'ScriptDomain_594C2060' ...
[03:45:02] [DEBUG] Started script 'GTA.GangAndTurfMod.ModCore'.
[03:45:02] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_594C2060' ...
[03:45:02] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[03:45:02] [DEBUG] Instantiating script 'TriggerHappy.TriggerHappy' in script domain 'ScriptDomain_594C2060' ...
[03:45:02] [DEBUG] Started script 'TriggerHappy.TriggerHappy'.
[04:38:08] [DEBUG] Created script domain 'ScriptDomain_933CAB82' with v2.9.2.
[04:38:08] [DEBUG] Loading scripts from 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_933CAB82' ...
[04:38:08] [DEBUG] Found 3 script(s) in 'GangAndTurfMod.dll'.
[04:38:08] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[04:38:08] [DEBUG] Found 1 script(s) in 'TriggerHappy.dll'.
[04:38:08] [DEBUG] Starting 5 script(s) ...
[04:38:08] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner' in script domain 'ScriptDomain_933CAB82' ...
[04:38:08] [DEBUG] Started script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner'.
[04:38:08] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.GangWarManager' in script domain 'ScriptDomain_933CAB82' ...
[04:38:08] [DEBUG] Started script 'GTA.GangAndTurfMod.GangWarManager'.
[04:38:08] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.ModCore' in script domain 'ScriptDomain_933CAB82' ...
[04:38:09] [DEBUG] Started script 'GTA.GangAndTurfMod.ModCore'.
[04:38:09] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_933CAB82' ...
[04:38:09] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[04:38:09] [DEBUG] Instantiating script 'TriggerHappy.TriggerHappy' in script domain 'ScriptDomain_933CAB82' ...
[04:38:09] [DEBUG] Started script 'TriggerHappy.TriggerHappy'.
[07:02:26] [DEBUG] Created script domain 'ScriptDomain_BD50933C' with v2.9.2.
[07:02:26] [DEBUG] Loading scripts from 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_BD50933C' ...
[07:02:26] [DEBUG] Found 3 script(s) in 'GangAndTurfMod.dll'.
[07:02:27] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[07:02:27] [DEBUG] Found 1 script(s) in 'TriggerHappy.dll'.
[07:02:27] [DEBUG] Starting 5 script(s) ...
[07:02:27] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner' in script domain 'ScriptDomain_BD50933C' ...
[07:02:27] [DEBUG] Started script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner'.
[07:02:27] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.GangWarManager' in script domain 'ScriptDomain_BD50933C' ...
[07:02:27] [DEBUG] Started script 'GTA.GangAndTurfMod.GangWarManager'.
[07:02:27] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.ModCore' in script domain 'ScriptDomain_BD50933C' ...
[07:02:27] [DEBUG] Started script 'GTA.GangAndTurfMod.ModCore'.
[07:02:27] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_BD50933C' ...
[07:02:27] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[07:02:27] [DEBUG] Instantiating script 'TriggerHappy.TriggerHappy' in script domain 'ScriptDomain_BD50933C' ...
[07:02:27] [DEBUG] Started script 'TriggerHappy.TriggerHappy'.
[07:07:16] [DEBUG] Created script domain 'ScriptDomain_6BC84630' with v2.9.2.
[07:07:16] [DEBUG] Loading scripts from 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_6BC84630' ...
[07:07:16] [DEBUG] Found 3 script(s) in 'GangAndTurfMod.dll'.
[07:07:16] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[07:07:16] [DEBUG] Found 1 script(s) in 'TriggerHappy.dll'.
[07:07:16] [DEBUG] Starting 5 script(s) ...
[07:07:16] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner' in script domain 'ScriptDomain_6BC84630' ...
[07:07:16] [DEBUG] Started script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner'.
[07:07:16] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.GangWarManager' in script domain 'ScriptDomain_6BC84630' ...
[07:07:16] [DEBUG] Started script 'GTA.GangAndTurfMod.GangWarManager'.
[07:07:16] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.ModCore' in script domain 'ScriptDomain_6BC84630' ...
[07:07:17] [DEBUG] Started script 'GTA.GangAndTurfMod.ModCore'.
[07:07:17] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_6BC84630' ...
[07:07:17] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[07:07:17] [DEBUG] Instantiating script 'TriggerHappy.TriggerHappy' in script domain 'ScriptDomain_6BC84630' ...
[07:07:17] [DEBUG] Started script 'TriggerHappy.TriggerHappy'.
[07:29:07] [ERROR] Caught fatal unhandled exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at GTA.GangAndTurfMod.ZoneManager.GetRandomZone(Boolean preferablyNeutralZone)
   at GTA.GangAndTurfMod.GangAI.Update()
   at GTA.GangAndTurfMod.GangManager.TickGangs()
   at GTA.GangAndTurfMod.GangManager.Tick()
   at GTA.GangAndTurfMod.ModCore.OnTick(Object sender, EventArgs e)
   at GTA.Script.raise_Tick(Object value0, EventArgs value1)
   at GTA.Script.MainLoop()
[15:28:11] [DEBUG] Created script domain 'ScriptDomain_309E5EE4' with v2.9.2.
[15:28:11] [DEBUG] Loading scripts from 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_309E5EE4' ...
[15:28:11] [DEBUG] Found 3 script(s) in 'GangAndTurfMod.dll'.
[15:28:11] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[15:28:11] [DEBUG] Found 1 script(s) in 'TriggerHappy.dll'.
[15:28:11] [DEBUG] Starting 5 script(s) ...
[15:28:11] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner' in script domain 'ScriptDomain_309E5EE4' ...
[15:28:11] [DEBUG] Started script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner'.
[15:28:11] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.GangWarManager' in script domain 'ScriptDomain_309E5EE4' ...
[15:28:11] [DEBUG] Started script 'GTA.GangAndTurfMod.GangWarManager'.
[15:28:11] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.ModCore' in script domain 'ScriptDomain_309E5EE4' ...
[15:28:12] [DEBUG] Started script 'GTA.GangAndTurfMod.ModCore'.
[15:28:12] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_309E5EE4' ...
[15:28:12] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[15:28:12] [DEBUG] Instantiating script 'TriggerHappy.TriggerHappy' in script domain 'ScriptDomain_309E5EE4' ...
[15:28:12] [DEBUG] Started script 'TriggerHappy.TriggerHappy'.
[16:11:10] [ERROR] Caught fatal unhandled exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at GTA.GangAndTurfMod.ZoneManager.GetRandomZone(Boolean preferablyNeutralZone)
   at GTA.GangAndTurfMod.GangAI.Update()
   at GTA.GangAndTurfMod.GangManager.TickGangs()
   at GTA.GangAndTurfMod.GangManager.Tick()
   at GTA.GangAndTurfMod.ModCore.OnTick(Object sender, EventArgs e)
   at GTA.Script.raise_Tick(Object value0, EventArgs value1)
   at GTA.Script.MainLoop()
[16:12:18] [DEBUG] Unloading script domain 'ScriptDomain_309E5EE4' ...
[16:12:18] [DEBUG] Stopping 5 script(s) ...
[16:12:18] [DEBUG] Aborted script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner'.
[16:12:18] [DEBUG] Aborted script 'GTA.GangAndTurfMod.GangWarManager'.
[16:12:18] [DEBUG] Aborted script 'GTA.GangAndTurfMod.ModCore'.
[16:12:18] [DEBUG] Aborted script 'NativeUI.BigMessageThread'.
[16:12:18] [DEBUG] Aborted script 'TriggerHappy.TriggerHappy'.
[16:12:18] [ERROR] Caught fatal unhandled exception:
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at GTA.Script.Wait(Int32 ms)
   at GTA.GangAndTurfMod.AmbientGangMemberSpawner.OnTick(Object sender, EventArgs e)
   at GTA.Script.raise_Tick(Object value0, EventArgs value1)
   at GTA.Script.MainLoop()
[16:12:18] [DEBUG] Deleted script domain 'ScriptDomain_309E5EE4'.
[16:12:18] [DEBUG] Created script domain 'ScriptDomain_3F6A739A' with v2.9.2.
[16:12:18] [DEBUG] Loading scripts from 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_3F6A739A' ...
[16:12:18] [DEBUG] Found 3 script(s) in 'GangAndTurfMod.dll'.
[16:12:18] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[16:12:18] [DEBUG] Found 1 script(s) in 'TriggerHappy.dll'.
[16:12:18] [DEBUG] Starting 5 script(s) ...
[16:12:18] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner' in script domain 'ScriptDomain_3F6A739A' ...
[16:12:18] [DEBUG] Started script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner'.
[16:12:18] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.GangWarManager' in script domain 'ScriptDomain_3F6A739A' ...
[16:12:18] [DEBUG] Started script 'GTA.GangAndTurfMod.GangWarManager'.
[16:12:18] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.ModCore' in script domain 'ScriptDomain_3F6A739A' ...
[16:12:19] [DEBUG] Started script 'GTA.GangAndTurfMod.ModCore'.
[16:12:19] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_3F6A739A' ...
[16:12:19] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[16:12:19] [DEBUG] Instantiating script 'TriggerHappy.TriggerHappy' in script domain 'ScriptDomain_3F6A739A' ...
[16:12:19] [DEBUG] Started script 'TriggerHappy.TriggerHappy'.
[16:24:40] [ERROR] Caught fatal unhandled exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at GTA.GangAndTurfMod.ZoneManager.GetRandomZone(Boolean preferablyNeutralZone)
   at GTA.GangAndTurfMod.GangAI.Update()
   at GTA.GangAndTurfMod.GangManager.TickGangs()
   at GTA.GangAndTurfMod.GangManager.Tick()
   at GTA.GangAndTurfMod.ModCore.OnTick(Object sender, EventArgs e)
   at GTA.Script.raise_Tick(Object value0, EventArgs value1)
   at GTA.Script.MainLoop()
[16:58:56] [DEBUG] Created script domain 'ScriptDomain_91BC60AE' with v2.9.2.
[16:58:56] [DEBUG] Loading scripts from 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_91BC60AE' ...
[16:58:57] [DEBUG] Found 3 script(s) in 'GangAndTurfMod.dll'.
[16:58:57] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[16:58:57] [DEBUG] Found 1 script(s) in 'TriggerHappy.dll'.
[16:58:57] [DEBUG] Starting 5 script(s) ...
[16:58:57] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner' in script domain 'ScriptDomain_91BC60AE' ...
[16:58:57] [DEBUG] Started script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner'.
[16:58:57] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.GangWarManager' in script domain 'ScriptDomain_91BC60AE' ...
[16:58:57] [DEBUG] Started script 'GTA.GangAndTurfMod.GangWarManager'.
[16:58:57] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.ModCore' in script domain 'ScriptDomain_91BC60AE' ...
[16:58:57] [DEBUG] Started script 'GTA.GangAndTurfMod.ModCore'.
[16:58:57] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_91BC60AE' ...
[16:58:57] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[16:58:57] [DEBUG] Instantiating script 'TriggerHappy.TriggerHappy' in script domain 'ScriptDomain_91BC60AE' ...
[16:58:57] [DEBUG] Started script 'TriggerHappy.TriggerHappy'.
[17:17:21] [DEBUG] Unloading script domain 'ScriptDomain_91BC60AE' ...
[17:17:21] [DEBUG] Stopping 5 script(s) ...
[17:17:21] [DEBUG] Aborted script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner'.
[17:17:21] [ERROR] Caught fatal unhandled exception:
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at GTA.Script.Wait(Int32 ms)
   at GTA.GangAndTurfMod.AmbientGangMemberSpawner.OnTick(Object sender, EventArgs e)
   at GTA.Script.raise_Tick(Object value0, EventArgs value1)
   at GTA.Script.MainLoop()
[17:17:21] [DEBUG] Aborted script 'GTA.GangAndTurfMod.GangWarManager'.
[17:17:21] [DEBUG] Aborted script 'GTA.GangAndTurfMod.ModCore'.
[17:17:21] [DEBUG] Aborted script 'NativeUI.BigMessageThread'.
[17:17:21] [DEBUG] Aborted script 'TriggerHappy.TriggerHappy'.
[17:17:21] [DEBUG] Deleted script domain 'ScriptDomain_91BC60AE'.
[17:17:22] [DEBUG] Created script domain 'ScriptDomain_8FA162C2' with v2.9.2.
[17:17:22] [DEBUG] Loading scripts from 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_8FA162C2' ...
[17:17:22] [DEBUG] Found 3 script(s) in 'GangAndTurfMod.dll'.
[17:17:22] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[17:17:22] [DEBUG] Found 1 script(s) in 'TriggerHappy.dll'.
[17:17:22] [DEBUG] Starting 5 script(s) ...
[17:17:22] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner' in script domain 'ScriptDomain_8FA162C2' ...
[17:17:22] [DEBUG] Started script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner'.
[17:17:22] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.GangWarManager' in script domain 'ScriptDomain_8FA162C2' ...
[17:17:22] [DEBUG] Started script 'GTA.GangAndTurfMod.GangWarManager'.
[17:17:22] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.ModCore' in script domain 'ScriptDomain_8FA162C2' ...
[17:17:23] [DEBUG] Started script 'GTA.GangAndTurfMod.ModCore'.
[17:17:23] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_8FA162C2' ...
[17:17:23] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[17:17:23] [DEBUG] Instantiating script 'TriggerHappy.TriggerHappy' in script domain 'ScriptDomain_8FA162C2' ...
[17:17:23] [DEBUG] Started script 'TriggerHappy.TriggerHappy'.
[20:11:25] [DEBUG] Created script domain 'ScriptDomain_EC014B62' with v2.9.2.
[20:11:25] [DEBUG] Loading scripts from 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_EC014B62' ...
[20:11:25] [DEBUG] Found 3 script(s) in 'GangAndTurfMod.dll'.
[20:11:25] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[20:11:25] [DEBUG] Found 1 script(s) in 'TriggerHappy.dll'.
[20:11:25] [DEBUG] Starting 5 script(s) ...
[20:11:25] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner' in script domain 'ScriptDomain_EC014B62' ...
[20:11:25] [DEBUG] Started script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner'.
[20:11:25] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.GangWarManager' in script domain 'ScriptDomain_EC014B62' ...
[20:11:25] [DEBUG] Started script 'GTA.GangAndTurfMod.GangWarManager'.
[20:11:25] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.ModCore' in script domain 'ScriptDomain_EC014B62' ...
[20:11:26] [DEBUG] Started script 'GTA.GangAndTurfMod.ModCore'.
[20:11:26] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_EC014B62' ...
[20:11:26] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[20:11:26] [DEBUG] Instantiating script 'TriggerHappy.TriggerHappy' in script domain 'ScriptDomain_EC014B62' ...
[20:11:26] [DEBUG] Started script 'TriggerHappy.TriggerHappy'.
[20:34:53] [DEBUG] Created script domain 'ScriptDomain_3D7767FC' with v2.9.2.
[20:34:53] [DEBUG] Loading scripts from 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_3D7767FC' ...
[20:34:53] [DEBUG] Found 3 script(s) in 'GangAndTurfMod.dll'.
[20:34:53] [DEBUG] Found 1 script(s) in 'NativeUI.dll'.
[20:34:53] [DEBUG] Found 1 script(s) in 'TriggerHappy.dll'.
[20:34:53] [DEBUG] Starting 5 script(s) ...
[20:34:53] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner' in script domain 'ScriptDomain_3D7767FC' ...
[20:34:53] [DEBUG] Started script 'GTA.GangAndTurfMod.AmbientGangMemberSpawner'.
[20:34:53] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.GangWarManager' in script domain 'ScriptDomain_3D7767FC' ...
[20:34:53] [DEBUG] Started script 'GTA.GangAndTurfMod.GangWarManager'.
[20:34:53] [DEBUG] Instantiating script 'GTA.GangAndTurfMod.ModCore' in script domain 'ScriptDomain_3D7767FC' ...
[20:34:54] [DEBUG] Started script 'GTA.GangAndTurfMod.ModCore'.
[20:34:54] [DEBUG] Instantiating script 'NativeUI.BigMessageThread' in script domain 'ScriptDomain_3D7767FC' ...
[20:34:54] [DEBUG] Started script 'NativeUI.BigMessageThread'.
[20:34:54] [DEBUG] Instantiating script 'TriggerHappy.TriggerHappy' in script domain 'ScriptDomain_3D7767FC' ...
[20:34:54] [DEBUG] Started script 'TriggerHappy.TriggerHappy'.

**Comment by lucasvinbr** [comment]
Hahaha thanks a lot for reporting this issue, it's definitely a problem. I'll try to fix it ASAP

**Comment by freakyneek** [comment]
This is the first time I would donate to a programmer, but out of all the mods I've played, I think you deserve a donation. If you ever put up a donation account, I would gladly give you some of my dollars. I just have one request for your mod: Could you add an option to limit certain weapons? Gangs with grenades/grenade launchers/rpgs are near impossible to beat.

**Comment by lucasvinbr** [comment]
ahahaha thanks, hehe. About the issue, are you still having it on the new version (1.2.1)?
About limiting those weapons, the gangs would still be able to use them, but only a few members?
Currently, you can edit the ModOptions file to make it impossible for gangs to purchase a certain weapon (you'd have to edit the GangData file and remove it from gangs that have already bought it too)

**Comment by freakyneek** [comment]
The new version is fixed. I edited the gangdata file and removed the grenade launcher and rail gun. I hope that makes the gangs easier to battle.

**Comment by lucasvinbr** [comment]
Nice! I'll close this issue then, and I'll try to look into limiting the number of enemies with a specific weapon
